load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "grpcdemo",
    srcs = ["service.go"],
    importpath = "grouter/services/grpcdemosvc/internal/pkg/grpcdemo",
    visibility = ["//services/grpcdemosvc:__subpackages__"],
    deps = [
        "//pkg/manager",
        "//pkg/messaging/grpc",
        "//services/grpcdemosvc/api/proto",
        "@com_github_go_viper_mapstructure_v2//:mapstructure",
        "@org_golang_google_grpc//:grpc",
        "@org_uber_go_zap//:zap",
    ],
)
