load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "app",
    srcs = ["app.go"],
    importpath = "grouter/templates/messaging-rpc-service/internal/app",
    visibility = ["//templates/messaging-rpc-service:__subpackages__"],
    deps = [
        "//pkg/manager",
        "//templates/grpc-service/api/proto",
        "//pkg/messaging/grpc",
        "//pkg/messaging/nats",
        "//templates/messaging-rpc-service/internal/config",
        "//templates/messaging-rpc-service/internal/grpc",
        "//templates/messaging-rpc-service/internal/pkg/api",
        "@org_golang_google_grpc//:grpc",
    ],
)
