load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "users",
    srcs = ["service.go"],
    importpath = "grouter/templates/nats-service/internal/pkg/users",
    visibility = ["//templates/nats-service:__subpackages__"],
    deps = [
        "//pkg/manager",
        "//pkg/messaging/nats",
        "@org_uber_go_zap//:zap",
    ],
)
