load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "grpc",
    srcs = ["server.go"],
    importpath = "grouter/templates/grpc-service/internal/grpc",
    visibility = ["//templates/grpc-service:__subpackages__"],
    deps = [
        "//templates/grpc-service/api/proto",
        "@org_uber_go_zap//:zap",
    ],
)
