load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "products",
    srcs = [
        "model.go",
        "repository.go",
    ],
    importpath = "grouter/templates/db-service/internal/pkg/products",
    visibility = ["//templates/db-service:__subpackages__"],
    deps = [
        "//pkg/database",
        "//templates/db-service/api/v1:api",
        "@io_gorm_gorm//:gorm",
        "@io_gorm_gorm//clause",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)

go_test(
    name = "products_test",
    srcs = ["products_test.go"],
    embed = [":products"],
    deps = [
        "//templates/db-service/api/v1:api",
        "@com_github_stretchr_testify//assert",
    ],
)
