load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "proto_proto",
    srcs = ["hello.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "proto_go_proto",
    compilers = ["@rules_go//proto:go_grpc"],
    importpath = "grouter/templates/grpc-service/api/proto",
    proto = ":proto_proto",
    visibility = ["//visibility:public"],
)
