load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "client_lib",
    srcs = ["main.go"],
    importpath = "grouter/templates/hybrid-service/cmd/client",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/config",
        "//pkg/logger",
        "//pkg/messaging/nats",
        "@org_uber_go_zap//:zap",
    ],
)

go_binary(
    name = "client",
    embed = [":client_lib"],
    visibility = ["//visibility:public"],
)
