load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "users",
    srcs = ["handler.go"],
    importpath = "grouter/templates/rest-service/internal/pkg/users",
    visibility = ["//templates/rest-service:__subpackages__"],
    deps = [
        "//pkg/manager",
        "@com_github_gin_gonic_gin//:gin",
        "@org_uber_go_zap//:zap",
    ],
)
