package grpc

import (
	"context"
	"fmt"
	"net"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/reflection"
)

// Server wraps a standard gRPC server and an optional gRPC-Gateway.
type Server struct {
	server       *grpc.Server
	listener     net.Listener
	port         int
	logger       *zap.Logger
	reflection   bool
	gateway      bool
	gatewayCtx   context.Context
	gatewayMux   *runtime.ServeMux
	gatewayPorts []int // Port(s) for the gateway to listen on usually just one
	gatewaySrv   *http.Server

	// Keep track of registered gateway handlers to call them during Start
	gatewayRegistrars []func(context.Context, *runtime.ServeMux, string, []grpc.DialOption) error

	// Keep track of service registration functions to call after server is created
	serviceRegistrars []func(grpc.ServiceRegistrar)

	// Configuration
	config ServerConfig

	// Interceptors
	unaryInterceptors  []UnaryServerInterceptor
	streamInterceptors []StreamServerInterceptor
	serverOptions      []grpc.ServerOption
}

// Option defines a functional option for configuring the Server.
type Option func(*Server)

// WithPort sets the port for the gRPC server.
func WithPort(port int) Option {
	return func(s *Server) {
		s.port = port
	}
}

// WithReflection enables gRPC server reflection.
func WithReflection() Option {
	return func(s *Server) {
		s.reflection = true
	}
}

// WithGateway enables the gRPC-Gateway on a specific port.
// It proxies requests to the gRPC server running on the main port.
func WithGateway(ctx context.Context, port int, muxOptions ...runtime.ServeMuxOption) Option {
	return func(s *Server) {
		s.gateway = true
		s.gatewayCtx = ctx
		s.gatewayMux = runtime.NewServeMux(muxOptions...)
		s.gatewayPorts = append(s.gatewayPorts, port)
	}
}

// WithInterceptors adds unary and stream interceptors to the server.
func WithInterceptors(unary []UnaryServerInterceptor, stream []StreamServerInterceptor) Option {
	return func(s *Server) {
		s.unaryInterceptors = append(s.unaryInterceptors, unary...)
		s.streamInterceptors = append(s.streamInterceptors, stream...)
	}
}

// WithUnaryInterceptor adds a unary interceptor to the server.
func WithUnaryInterceptor(interceptor UnaryServerInterceptor) Option {
	return func(s *Server) {
		s.unaryInterceptors = append(s.unaryInterceptors, interceptor)
	}
}

// WithStreamInterceptor adds a stream interceptor to the server.
func WithStreamInterceptor(interceptor StreamServerInterceptor) Option {
	return func(s *Server) {
		s.streamInterceptors = append(s.streamInterceptors, interceptor)
	}
}

// WithServerOptions adds server additional gRPC server options.
func WithServerOptions(opts ...grpc.ServerOption) Option {
	return func(s *Server) {
		s.serverOptions = append(s.serverOptions, opts...)
	}
}

// NewServer creates a new gRPC Server with the given options.
func NewServer(logger *zap.Logger, opts ...Option) *Server {
	s := &Server{
		logger: logger,
		// Default port if not provided? standard gRPC often uses 50051, but let's leave it 0 (dynamic) or require it.
		// For now, if 0, net.Listen will handle it, but we better default or expect it.
		// Defaulting to 9090 since 8080 is often web.
		port: 9090,
	}

	// Apply user options
	for _, opt := range opts {
		opt(s)
	}

	// Build server options with interceptors
	serverOpts := []grpc.ServerOption{}
	serverOpts = append(serverOpts, s.serverOptions...)

	// Add interceptors if provided
	if len(s.unaryInterceptors) > 0 {
		serverOpts = append(serverOpts, grpc.ChainUnaryInterceptor(s.unaryInterceptors...))
	}
	if len(s.streamInterceptors) > 0 {
		serverOpts = append(serverOpts, grpc.ChainStreamInterceptor(s.streamInterceptors...))
	}

	s.server = grpc.NewServer(serverOpts...)

	if s.reflection {
		reflection.Register(s.server)
	}

	return s
}

// RegisterService registers a service implementation with the gRPC server.
// The registration function is typically generated by protoc-gen-go-grpc.
func (s *Server) RegisterService(reg func(grpc.ServiceRegistrar)) {
	s.serviceRegistrars = append(s.serviceRegistrars, reg)
}

// RegisterGatewayHandler registers a gRPC-Gateway handler.
// The handler function is typically generated by protoc-gen-grpc-gateway.
func (s *Server) RegisterGatewayHandler(handler func(context.Context, *runtime.ServeMux, string, []grpc.DialOption) error) {
	s.gatewayRegistrars = append(s.gatewayRegistrars, handler)
}

// Start starts the gRPC server and optionally the gRPC-Gateway.
func (s *Server) Start() error {
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", s.port))
	if err != nil {
		return fmt.Errorf("failed to listen on port %d: %w", s.port, err)
	}
	s.listener = lis

	// Update port if it was 0 (dynamic allocation)
	if s.port == 0 {
		s.port = s.listener.Addr().(*net.TCPAddr).Port
	}

	// Build server options
	var opts []grpc.ServerOption

	// Add TLS credentials if enabled
	if s.config.TLS.Enabled {
		creds, err := configureTLS(s.config.TLS)
		if err != nil {
			return fmt.Errorf("failed to configure TLS: %w", err)
		}
		opts = append(opts, grpc.Creds(creds))
		s.logger.Info("TLS enabled for gRPC server",
			zap.String("cert", s.config.TLS.CertFile),
			zap.Bool("client_auth", s.config.TLS.ClientAuth),
		)
	}

	// Add interceptors
	if len(s.unaryInterceptors) > 0 {
		opts = append(opts, grpc.ChainUnaryInterceptor(s.unaryInterceptors...))
	}
	if len(s.streamInterceptors) > 0 {
		opts = append(opts, grpc.ChainStreamInterceptor(s.streamInterceptors...))
	}

	// Add any custom server options
	opts = append(opts, s.serverOptions...)

	// Create gRPC server
	s.server = grpc.NewServer(opts...)

	// Register all stored services
	for _, reg := range s.serviceRegistrars {
		reg(s.server)
	}

	// Enable reflection if configured
	if s.reflection {
		reflection.Register(s.server)
		s.logger.Info("gRPC server reflection enabled")
	}

	// Start gRPC server in goroutine
	go func() {
		s.logger.Info("Starting gRPC server", zap.Int("port", s.port))
		if err := s.server.Serve(lis); err != nil {
			s.logger.Error("gRPC server error", zap.Error(err))
		}
	}()

	// Start gateway if enabled
	if s.gateway {
		return s.startGateway()
	}

	return nil
}

func (s *Server) startGateway() error {
	// Connect to the gRPC server
	// We dial localhost:port
	grpcAddr := fmt.Sprintf("localhost:%d", s.port)
	opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}

	// Register all handlers
	for _, reg := range s.gatewayRegistrars {
		if err := reg(s.gatewayCtx, s.gatewayMux, grpcAddr, opts); err != nil {
			return fmt.Errorf("failed to register gateway handler: %w", err)
		}
	}

	gatewayPort := s.gatewayPorts[0] // Support multiple? Just one for now usually.

	s.gatewaySrv = &http.Server{
		Addr:    fmt.Sprintf(":%d", gatewayPort),
		Handler: s.gatewayMux,
	}

	s.logger.Info("Starting gRPC-Gateway", zap.Int("port", gatewayPort))

	go func() {
		if err := s.gatewaySrv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			s.logger.Error("gRPC-Gateway stopped", zap.Error(err))
		}
	}()

	return nil
}

// Stop gracefully stops the server(s).
func (s *Server) Stop(ctx context.Context) {
	s.logger.Info("Stopping gRPC server")
	s.server.GracefulStop()

	if s.gatewaySrv != nil {
		s.logger.Info("Stopping gRPC-Gateway")
		if err := s.gatewaySrv.Shutdown(ctx); err != nil {
			s.logger.Error("Failed to shutdown gateway", zap.Error(err))
		}
	}
}
