load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "app",
    srcs = ["app.go"],
    importpath = "grouter/services/grpcdemosvc/internal/app",
    visibility = ["//services/grpcdemosvc:__subpackages__"],
    deps = [
        "//pkg/config",
        "//pkg/logger",
        "//pkg/manager",
        "@com_github_google_uuid//:uuid",
        "@org_uber_go_zap//:zap",
    ],
)
