load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "manager",
    srcs = [
        "capabilities.go",
        "deps.go",
        "factory.go",
        "manager.go",
        "store.go",
        "types.go",
    ],
    importpath = "grouter/pkg/manager",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/config",
        "//pkg/messaging/nats",
        "@com_github_go_viper_mapstructure_v2//:mapstructure",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "manager_test",
    srcs = [
        "manager_test.go",
        "store_test.go",
    ],
    embed = [":manager"],
    deps = [
        "//pkg/config",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@org_uber_go_zap//:zap",
    ],
)
